# Generated by Django 3.2.3 on 2021-06-18 13:08

import board.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.TextField(help_text='재생목록 제목', max_length=150)),
                ('public_status', models.CharField(choices=[('0', 'Nothing'), ('1', 'Public'), ('2', 'Private'), ('3', 'Partial')], default=0, max_length=1, validators=[board.models.validate_public_status])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='board/post/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['avi', 'mp4', 'mkv', 'mpeg', 'webm'])])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='video_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['author'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('thumb_nail', models.ImageField(upload_to='board/post/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('description', models.TextField(blank=True, help_text='시청자에게 동영상에 대해 알려주세요', max_length=5000)),
                ('views_count', models.PositiveBigIntegerField(default=0)),
                ('public_status', models.CharField(choices=[('0', 'Nothing'), ('1', 'Public'), ('2', 'Private'), ('3', 'Partial')], default=0, max_length=1, validators=[board.models.validate_public_status])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='post_author', to=settings.AUTH_USER_MODEL)),
                ('post_group', models.ManyToManyField(blank=True, to='board.VideoGroup')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_video', to='board.video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(max_length=300)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.post')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
